import { AppData } from "@/lib/types";

export const seedData: AppData = {
  workspaces: [
    {
      id: "workspace-demo",
      name: "Northstar Labs",
      createdAt: "2025-01-12T10:00:00.000Z",
    },
  ],
  users: [
    {
      id: "admin-1",
      name: "Ava Chen",
      email: "admin@northstar.dev",
      passwordHash: "demo-admin",
      role: "ADMIN",
      workspaceId: "workspace-demo",
    },
    {
      id: "analyst-1",
      name: "Mina Patel",
      email: "analyst@northstar.dev",
      passwordHash: "demo-analyst",
      role: "ANALYST",
      workspaceId: "workspace-demo",
    },
    {
      id: "viewer-1",
      name: "Noah Brooks",
      email: "viewer@northstar.dev",
      passwordHash: "demo-viewer",
      role: "VIEWER",
      workspaceId: "workspace-demo",
    },
  ],
  themes: [
    { id: "theme-onboarding", name: "Onboarding", description: "Setup and first-use friction", color: "#f97316", workspaceId: "workspace-demo" },
    { id: "theme-analytics", name: "Analytics", description: "Insights and dashboard usability", color: "#3b82f6", workspaceId: "workspace-demo" },
    { id: "theme-auth", name: "Authentication", description: "SSO, login, and access issues", color: "#8b5cf6", workspaceId: "workspace-demo" },
    { id: "theme-billing", name: "Billing", description: "Invoice and payments issues", color: "#10b981", workspaceId: "workspace-demo" },
    { id: "theme-mobile", name: "Mobile", description: "Mobile experience feedback", color: "#ef4444", workspaceId: "workspace-demo" },
  ],
  feedback: [
    {
      id: "fb-1",
      content: "Onboarding took forever — I could not figure out how to invite my team.",
      channel: "Support ticket",
      sourceRef: "ticket-1001",
      customerLabel: "Acme Corp",
      sentiment: "NEG",
      sentimentScore: -0.94,
      status: "NEW",
      createdAt: "2025-02-10T10:00:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Onboarding"],
      featureArea: "Onboarding",
      rationale: "Customer described significant friction with team invite setup.",
    },
    {
      id: "fb-2",
      content: "The new dashboard is gorgeous and finally fast. Huge improvement.",
      channel: "App Store",
      sourceRef: "review-2003",
      customerLabel: "Lumen",
      sentiment: "POS",
      sentimentScore: 0.91,
      status: "REVIEWED",
      createdAt: "2025-02-11T13:00:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Analytics"],
      featureArea: "Dashboard",
      rationale: "Positive feedback about performance and visual quality.",
    },
    {
      id: "fb-3",
      content: "It does the job, but the mobile experience needs work.",
      channel: "NPS survey",
      sourceRef: "survey-3",
      customerLabel: "Peakly",
      sentiment: "NEU",
      sentimentScore: 0.02,
      status: "NEW",
      createdAt: "2025-02-12T07:15:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Mobile"],
      featureArea: "Mobile",
      rationale: "Neutral response highlighting a mobile experience issue.",
    },
    {
      id: "fb-4",
      content: "Prospect wants SSO before they will sign — this has come up three times this month.",
      channel: "Sales call",
      sourceRef: "call-88",
      customerLabel: "Northwind",
      sentiment: "NEG",
      sentimentScore: -0.89,
      status: "ACTIONED",
      createdAt: "2025-02-13T08:00:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Authentication"],
      featureArea: "SSO",
      rationale: "Recurring blocker for enterprise sales due to lack of SSO support.",
    },
    {
      id: "fb-5",
      content: "Love the new export feature, saved me an hour today.",
      channel: "Community post",
      sourceRef: "community-51",
      customerLabel: "BrightPath",
      sentiment: "POS",
      sentimentScore: 0.83,
      status: "REVIEWED",
      createdAt: "2025-02-16T11:20:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Analytics"],
      featureArea: "Exports",
      rationale: "User praised the export workflow and efficiency gain.",
    },
    {
      id: "fb-6",
      content: "Billing page keeps timing out when I try to download an invoice.",
      channel: "Support ticket",
      sourceRef: "ticket-1010",
      customerLabel: "Harbor Labs",
      sentiment: "NEG",
      sentimentScore: -0.96,
      status: "NEW",
      createdAt: "2025-02-18T12:40:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Billing"],
      featureArea: "Billing",
      rationale: "Customer reported invoice download timing out on billing page.",
    },
    {
      id: "fb-7",
      content: "The onboarding checklist is still confusing. I need more guidance on where to start.",
      channel: "Support ticket",
      sourceRef: "ticket-1020",
      customerLabel: "Moss",
      sentiment: "NEG",
      sentimentScore: -0.85,
      status: "NEW",
      createdAt: "2025-02-20T09:30:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Onboarding"],
      featureArea: "Onboarding",
      rationale: "Users need clearer guidance and next steps during onboarding.",
    },
    {
      id: "fb-8",
      content: "Our team loves the reporting snapshots, but filtering by campaign is still clunky.",
      channel: "NPS survey",
      sourceRef: "survey-11",
      customerLabel: "Northstar",
      sentiment: "NEU",
      sentimentScore: 0.03,
      status: "REVIEWED",
      createdAt: "2025-02-21T16:30:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Analytics"],
      featureArea: "Reporting",
      rationale: "Response mixed, but highlights reporting filter pain.",
    },
    {
      id: "fb-9",
      content: "SSO still feels inconsistent between desktop and mobile. Please fix it.",
      channel: "App Store",
      sourceRef: "review-2012",
      customerLabel: "Blueleaf",
      sentiment: "NEG",
      sentimentScore: -0.82,
      status: "NEW",
      createdAt: "2025-02-22T10:10:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Authentication"],
      featureArea: "SSO",
      rationale: "Customer flagged inconsistent SSO behavior across mobile and desktop.",
    },
    {
      id: "fb-10",
      content: "The app feels much more responsive on mobile this week. Great work.",
      channel: "Community post",
      sourceRef: "community-63",
      customerLabel: "Tidal Ops",
      sentiment: "POS",
      sentimentScore: 0.88,
      status: "ACTIONED",
      createdAt: "2025-02-24T12:05:00.000Z",
      workspaceId: "workspace-demo",
      themes: ["Mobile"],
      featureArea: "Mobile",
      rationale: "Positive feedback about mobile responsiveness improvements.",
    },
  ],
  reports: [
    {
      id: "report-1",
      title: "Weekly Voice of Customer Report",
      periodStart: "2025-02-10",
      periodEnd: "2025-02-24",
      contentJson: JSON.stringify({
        summary: "Onboarding and authentication issues dominate the feedback stream this week.",
        themes: ["Onboarding", "Authentication"],
        quotes: ["Onboarding took forever", "SSO before they will sign"],
      }),
      createdAt: "2025-02-24T18:00:00.000Z",
      workspaceId: "workspace-demo",
      generatedBy: "admin-1",
    },
  ],
};
